const INTERVIEW_STATUS = {
  PROGRAMAT: "PROGRAMAT",
  FINALIZAT: "FINALIZAT",
  ANULAT: "ANULAT",
  REPROGRAMARE_SOLICITATA: "REPROGRAMARE_SOLICITATA",
  NEPREZENTAT: "NEPREZENTAT"
};

module.exports = INTERVIEW_STATUS;
