const INTERVIEW_TYPES = {
  HR_ONLINE: "HR_ONLINE",
  HR_FIZIC: "HR_FIZIC",
  HR_TELEFONIC: "HR_TELEFONIC",
  TEHNIC_ONLINE: "TEHNIC_ONLINE",
  TEHNIC_FIZIC: "TEHNIC_FIZIC"
};

module.exports = INTERVIEW_TYPES;
